- platform: hyperion
  host: 192.168.1.7
  name: TV Hyperion
  effect_list:
    - "HDMI"
    - "Audio Visualizer"
    - "Cinema brighten lights"
    - "Cinema dim lights"
    - "Knight rider"
    - "Blue mood blobs"
    - "Cold mood blobs"
    - "Full color mood blobs"
    - "Green mood blobs"
    - "Red mood blobs"
    - "Warm mood blobs"
    - "Police Lights Single"
    - "Police Lights Solid"
    - "Rainbow mood"
    - "Rainbow swirl fast"
    - "Rainbow swirl"
    - "Random"
    - "Running dots"
    - "System Shutdown"
    - "Snake"
    - "Sparks Color"
    - "Sparks"
    - "Strobe blue"
    - "Strobe Raspbmc"
    - "Strobe white"
    - "Color traces"
    - "UDP multicast listener"
    - "UDP listener"
    - "X-Mas"

