- alias: Alert of Garage Door Change
  trigger:
    platform: state
    entity_id: cover.garage_door
    from: 'closed'
    to: 'open'
  condition:
    condition: state
    entity_id: device_tracker.kevin_panaros_iphone_x
    state: not_home
  action:
    service: notify.ios_kevin_panaros_iphone_x
    data:
      title: "Garage Door"
      message: "The Garage Door Opened"
      data:
        push:
- alias: Alert Lengthy Open Garage Door
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'on'
    for:
      minutes: 30
  action:
    service: notify.ios_kevin_panaros_iphone_x
    data:
      title: "Garage Door"
      message: "The Garage Door has been open for 30 minutes"
      data:
        push:
