- alias: Alert of Garage Door Change
  trigger:
    platform: state
    entity_id: cover.garage_door
    from: 'closed'
    to: 'open'
  condition:
    condition: state
    entity_id: device_tracker.kevin_panaros_iphone_x
    state: not_home
  action:
    service: notify.ios_kevin_panaros_iphone_x
    data:
      title: "Garage Door"
      message: "The Garage Door Opened"
      data:
        push:
- alias: Alert Lengthy Open Garage Door
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'open'
    for: '00:30:00'
  action:
    service: notify.ios_kevin_panaros_iphone_x
    data:
      title: "Garage Door"
      message: "The Garage Door has been open for 30 minutes"
      data:
        push:
- alias: Alert if Garage Open after 9 PM
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    condition: state
    entity_id: cover.garage
    state: open
  action:
    service: notify.ios_kevin_panaros_iphone_x
    data:
      title: "Garage Door"
      message: "Garage Door is Open"
      data:
        push:
- alias: Close Garage Door on Weekdays
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'open'
    for: '00:10:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: cover.close_cover
    entity_id: cover.garage_door
